spring:
  jpa:
    hibernate:
      ddl-auto : create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ebanking
    username: root
    password: ayadi12345
  server:
    port: 8080
